version: '3.8'
services:
  postgres:
    build:
      context: ./docker
    image: pytest-tests/postgres
    hostname: postgres
    container_name: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    volumes:
      - pytest-tests-db-data:/var/lib/postgresql/data
      - ./docker:/tests/

volumes:
  pytest-tests-db-data: {}
